name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  security-events: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Install CLOC
      run: sudo apt-get update && sudo apt-get install -y cloc

    - name: Count Java lines of code
      id: count-loc
      run: cloc --include-lang=Java . > cloc_output.txt

    - name: Upload CLOC Output as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: CLOC-output
        path: cloc_output.txt

    - name: Send Email with CLOC Output as Attachment
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_SERVER }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: "${{ github.repository }}: Java Lines of Code Count"
        html_body: |
          <p>Build job nr ${{ github.run_number }} of <strong>${{ github.repository }}</strong> completed; Status: ${{ job.status }}</p>
          <p>The job ${{ github.job }} has been triggered by ${{ github.actor }} from a ${{ github.event_name}}</p>
          <p>The CLOC report is attached.</p>
          <br/> 
        from: ${{ secrets.SMTP_USERNAME }}
        to: ${{ secrets.TO_EMAIL }}
        content_type: text/plain
        attachments: cloc_output.txt
