name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build, test and check coverage with Maven
      run: mvn -B verify
    
    - name: Install CLOC
      run: sudo apt-get update && sudo apt-get install -y cloc

    - name: Count Java lines of code
      id: count-loc
      run: cloc --include-lang=Java . > cloc_output.txt

    - name: Send Email with Test and Coverage Results
      uses: dawidd6/action-send-mail@v3
      if: always()
      with:
        server_address: ${{ secrets.SMTP_SERVER }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: "${{ github.repository }}: Test Results and Code Coverage"
        html_body: |
          <h2>Build Results</h2>
          <p>Build job nr ${{ github.run_number }} of <strong>${{ github.repository }}</strong> completed; Status: ${{ job.status }}</p>
          <p>The job ${{ github.job }} has been triggered by ${{ github.actor }} from a ${{ github.event_name}}</p>
          
          <h3>Test Summary</h3>
          <p>All tests are run automatically with each commit and daily schedule.</p>
          <p>Test results and coverage reports are attached and available in GitHub Actions artifacts.</p>
          
          <h3>Code Quality</h3>
          <p>Line counting is performed automatically.</p>
          <p>The CLOC report is attached.</p>
          <br/>
        from: ${{ secrets.SMTP_USERNAME }}
        to: ${{ secrets.TO_EMAIL }}
        content_type: text/html
        attachments: |
          cloc_output.txt
          target/site/jacoco/index.html
