name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  security-events: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Install CLOC
      run: sudo apt-get update && sudo apt-get install -y cloc

    - name: Count Java lines of code
      run: cloc --include-lang=Java . > cloc_output.txt
    
    - name: Send Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_SERVER }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: Java Lines of Code Count
        body: |
          Here is the count of Java lines of code:
          
          $(cat cloc_output.txt)
        from: ${{ secrets.SMTP_USERNAME }}
        to: ${{ secrets.TO_EMAIL }}
        content_type: text/plain

          
          ${{ env.cloc_output }}
        from: ${{ secrets.SMTP_USERNAME }}
        to: ${{ secrets.TO_EMAIL }}

