name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  security-events: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Install CLOC
      run: sudo apt-get update && sudo apt-get install -y cloc

    - name: Count Java lines of code
      run: cloc --include-lang=Java . > cloc_output.txt
    
    - name: Send Email with CLOC Output
      run: |
        email_body=$(cat cloc_output.txt)
        echo "$email_body" | mail -s "Java Lines of Code Count" your-email@example.com
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
