name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  security-events: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Install CLOC
      run: sudo apt-get update && sudo apt-get install -y cloc

    - name: Count Java lines of code
      run: cloc --include-lang=Java . > cloc_output.txt

    - name: Send Email with CLOC Output
      run: |
        email_body=$(cat cloc_output.txt)
        echo "$email_body"
        echo "Sending email..."
        curl --request POST \
          --url https://api.sendgrid.com/v3/mail/send \
          --header "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
          --header "Content-Type: application/json" \
          --data '{
            "personalizations": [{
              "to": [{
                "email": "'"${{ secrets.TO_EMAIL }}"'"
              }],
              "subject": "Java Lines of Code Count"
            }],
            "from": {
              "email": "'"${{ secrets.SMTP_USERNAME }}"'"
            },
            "content": [{
              "type": "text/plain",
              "value": "'"$email_body"'"
            }]
          }'
